name: Fetch latest Mobilize data and update report

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/New_York
      - name: Check out this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Ruby 3.2.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true
      - name: Fetch latest vaccination sites
        run: bundle exec ruby mobilize-counter
        env:
          MOBILIZE_SESSION_ID: ${{ secrets.MOBILIZE_SESSION_ID }}
      - name: Commit and push if bus data changed
        run: |-
          if ! git diff --quiet; then
            git config user.name "Automated"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            timestamp=$(date -u)
            git commit -m "Latest data: ${timestamp}" || exit 0
            git push
          fi
